# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_foottype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foottype',
            table='axf_foottypes',
        ),
    ]
