# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190307_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foottype',
            new_name='Foodtype',
        ),
    ]
